apiVersion: bigquery.gcp.upbound.io/v1beta1
kind: Dataset
metadata:
  name: exampledataset
  # name: example.dataset   throws Google error
  # name: example-dataset   throws Google error
  # name: example_dataset   throws K8s error    
spec:
  forProvider:
    defaultTableExpirationMs: 3600000
    description: This is a test description
    friendlyName: example_dataset
    location: US
